name: Publish
on:
  workflow_dispatch:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
# adding R to original OF script        
      - name: Set up R  
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::readr
            any::tidyr
            any::readr
            any::stringr
            any::purrr
            any::jsonlite
            any::janitor
            any::glue
            any::tidytext
            any::lubridate
            any::httr
            any::curl
            
#          extra-packages: any::rcmdcheck
#          needs: check

#      - name: Install remotes
#        run: |
#          Rscript -e "install.packages('remotes', repos='https://ftp.belnet.be/mirror/CRAN')"

#      - name: Install package from Github
#        run: |
#          Rscript -e "remotes::install_github('aourednik/SPARQLchunks')"

#      - uses: r-lib/actions/check-r-package@v2


#      - name: Install dependencies
#        run: |
#          install.packages(c("remotes","testthat"),dependencies=TRUE)
#          remotes::install_github("aourednik/SPARQLchunks")
# end of r additions            

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
